language: perl

perl:
    - "5.22"
    - "5.14"
    - "5.10"

install:
    - dzil authordeps --missing | cpanm
    - dzil listdeps --author --missing | cpanm

sudo: false

script:
    - dzil test --author --release
